[profile.default]
solc_version = "0.8.24"
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "evc/=lib/ethereum-vault-connector/src/",
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
